
import java.sql.Connection;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.DefaultComboBoxModel;
import java.awt.Font;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author MoIYadah
 */
public class Bugzilla extends javax.swing.JFrame {

	/**
	 * Creates new form Main
	 */
	public Bugzilla() {
		initComponents();
		setLocationRelativeTo(null);
		hafizh();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jTextField1 = new javax.swing.JTextField();
		jPanel1 = new javax.swing.JPanel();
		jScrollPane1 = new javax.swing.JScrollPane();
		jTable1 = new javax.swing.JTable();
		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		jScrollPane2 = new javax.swing.JScrollPane();
		jTextArea1 = new javax.swing.JTextArea();
		jTextField2 = new javax.swing.JTextField();
		jComboBox1 = new javax.swing.JComboBox<>();
		jLabel3 = new javax.swing.JLabel();
		jLabel4 = new javax.swing.JLabel();
		jLabel5 = new javax.swing.JLabel();
		jButton1 = new javax.swing.JButton();
		jButton2 = new javax.swing.JButton();
		jButton3 = new javax.swing.JButton();
		jButton4 = new javax.swing.JButton();
		jButton5 = new javax.swing.JButton();
		jTextField3 = new javax.swing.JTextField();
		jLabel6 = new javax.swing.JLabel();
		jMenuBar1 = new javax.swing.JMenuBar();
		jMenu1 = new javax.swing.JMenu();
		jMenuItem2 = new javax.swing.JMenuItem();
		jMenu2 = new javax.swing.JMenu();
		jMenuItem3 = new javax.swing.JMenuItem();
		jMenu3 = new javax.swing.JMenu();
		jMenuItem4 = new javax.swing.JMenuItem();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setTitle("BugZilla");

		jPanel1.setBackground(new java.awt.Color(100, 200, 255));
		jPanel1.addKeyListener(new java.awt.event.KeyAdapter() {
			public void keyPressed(java.awt.event.KeyEvent evt) {
				jPanel1KeyPressed(evt);
			}
		});

		jTable1.setModel(
				new javax.swing.table.DefaultTableModel(
						new Object[][] { { null, null, null, null }, { null, null, null, null },
								{ null, null, null, null }, { null, null, null, null } },
						new String[] { "Title 1", "Title 2", "Title 3", "Title 4" }));
		jTable1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
		jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				jTable1MouseClicked(evt);
			}
		});
		jScrollPane1.setViewportView(jTable1);

		jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
		jLabel1.setText("BugZilla");

		jLabel2.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
		jLabel2.setText("The Bug Must Be Gone");

		jTextArea1.setColumns(20);
		jTextArea1.setRows(5);
		jScrollPane2.setViewportView(jTextArea1);

		jComboBox1.setModel(new DefaultComboBoxModel(new String[] {"\u95EE\u9898", "\u5DF2\u5904\u7406"}));
		jComboBox1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

		jLabel3.setFont(new Font("ËÎÌו", Font.PLAIN, 12)); // NOI18N
		jLabel3.setText("\u95EE\u9898\u63CF\u8FF0\uFF1A");

		jLabel4.setFont(new Font("ËÎÌו", Font.PLAIN, 12)); // NOI18N
		jLabel4.setText("\u95EE\u9898\u72B6\u6001");

		jLabel5.setFont(new Font("ËÎÌו", Font.PLAIN, 12)); // NOI18N
		jLabel5.setText("\u5904\u7406\u4EBA (\u5982\u6709)");

		jButton1.setText("\u6DFB\u52A0");
		jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});

		jButton2.setText("\u66F4\u65B0");
		jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
		jButton2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton2ActionPerformed(evt);
			}
		});

		jButton3.setText("\u5220\u9664");
		jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
		jButton3.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton3ActionPerformed(evt);
			}
		});

		jButton4.setText("\u91CD\u7F6E");
		jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
		jButton4.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton4ActionPerformed(evt);
			}
		});

		jButton5.setText("Refresh");
		jButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
		jButton5.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton5ActionPerformed(evt);
			}
		});

		jTextField3.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jTextField3ActionPerformed(evt);
			}
		});
		jTextField3.addKeyListener(new java.awt.event.KeyAdapter() {
			public void keyPressed(java.awt.event.KeyEvent evt) {
				jTextField3KeyPressed(evt);
			}
		});

		jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
		jLabel6.setText("Search");

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(jPanel1Layout.createSequentialGroup().addContainerGap(62, Short.MAX_VALUE)
										.addGroup(jPanel1Layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(jLabel3)
												.addGroup(jPanel1Layout
														.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING,
																false)
														.addComponent(jTextField2).addComponent(jLabel4)
														.addComponent(jScrollPane2,
																javax.swing.GroupLayout.DEFAULT_SIZE, 374,
																Short.MAX_VALUE)
														.addComponent(jComboBox1, 0,
																javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
												.addComponent(jLabel5)
												.addGroup(jPanel1Layout.createSequentialGroup().addComponent(jButton1)
														.addGap(18, 18, 18).addComponent(jButton2).addGap(18, 18, 18)
														.addComponent(jButton3).addGap(18, 18, 18)
														.addComponent(jButton4)))
										.addGap(102, 102, 102))
								.addGroup(jPanel1Layout.createSequentialGroup().addGap(121, 121, 121)
										.addComponent(jLabel1)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(jLabel2)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
												javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(jScrollPane1).addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
										jPanel1Layout.createSequentialGroup()
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
														javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
												.addComponent(jLabel6)
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
												.addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 227,
														javax.swing.GroupLayout.PREFERRED_SIZE)))
						.addContainerGap()));
		jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup().addContainerGap().addGroup(jPanel1Layout
						.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(jPanel1Layout.createSequentialGroup()
								.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(jLabel1).addComponent(jLabel2))
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addComponent(jLabel3)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(23, 23, 23).addComponent(jLabel4)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(23, 23, 23).addComponent(jLabel5)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(18, 18, 18)
								.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(jButton1).addComponent(jButton2).addComponent(jButton3)
										.addComponent(jButton4))
								.addGap(0, 94, Short.MAX_VALUE))
						.addGroup(jPanel1Layout.createSequentialGroup().addGap(0, 0, Short.MAX_VALUE)
								.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 25,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(jLabel6))
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 396,
										javax.swing.GroupLayout.PREFERRED_SIZE)))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(jButton5)
						.addContainerGap()));

		jMenuBar1.setBackground(new java.awt.Color(255, 200, 100));

		jMenu1.setText("File");

		jMenuItem2.setAccelerator(
				javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
		jMenuItem2.setText("Exit");
		jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jMenuItem2ActionPerformed(evt);
			}
		});
		jMenu1.add(jMenuItem2);

		jMenuBar1.add(jMenu1);

		jMenu2.setText("Edit");

		jMenuItem3.setText("Clear All");
		jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jMenuItem3ActionPerformed(evt);
			}
		});
		jMenu2.add(jMenuItem3);

		jMenuBar1.add(jMenu2);

		jMenu3.setText("Help");

		jMenuItem4.setText("About");
		jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jMenuItem4ActionPerformed(evt);
			}
		});
		jMenu3.add(jMenuItem4);

		jMenuBar1.add(jMenu3);

		setJMenuBar(jMenuBar1);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void load_table() {
		DefaultTableModel model = new DefaultTableModel();
		model.addColumn("ID");
		model.addColumn("Bug");
		model.addColumn("Status");
		model.addColumn("Solver");
		try {
			String sql = "select * from bug";
			java.sql.Connection conn = (Connection) Configuration.configDB();
			java.sql.Statement stm = conn.createStatement();
			java.sql.ResultSet res = stm.executeQuery(sql);
			while (res.next()) {
				model.addRow(new Object[] { res.getString(1), res.getString(2), res.getString(3), res.getString(4) });
			}
			jTable1.setModel(model);
		} catch (Exception e) {
		}
	}

	private void kosong() {
		jTextField1.setText(null);
		jTextField2.setText(null);
		jTextArea1.setText(null);
		jComboBox1.setSelectedItem("Problem");
	}

	private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton5ActionPerformed
		load_table();
	}// GEN-LAST:event_jButton5ActionPerformed

	private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jMenuItem2ActionPerformed
		System.exit(0);
	}// GEN-LAST:event_jMenuItem2ActionPerformed

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton1ActionPerformed
		try {
			String sql = "INSERT INTO bug (bug, status, solver) VALUES ('" + jTextArea1.getText() + "','"
					+ jComboBox1.getSelectedItem() + "','" + jTextField2.getText() + "')";
			java.sql.Connection conn = (Connection) Configuration.configDB();
			java.sql.PreparedStatement pst = conn.prepareStatement(sql);
			pst.execute();
			hafizh();
			JOptionPane.showMessageDialog(null, "Penyimpanan Data Berhasil");
		} catch (Exception e) {
			JOptionPane.showMessageDialog(this, "Error:" + e.getMessage());
		}
	}// GEN-LAST:event_jButton1ActionPerformed

	private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton4ActionPerformed
		kosong();
	}// GEN-LAST:event_jButton4ActionPerformed

	private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jMenuItem3ActionPerformed
		kosong();
	}// GEN-LAST:event_jMenuItem3ActionPerformed

	private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jMenuItem4ActionPerformed
		JOptionPane.showMessageDialog(null, "Created by :\n\nAbdullah Hafizh");
	}// GEN-LAST:event_jMenuItem4ActionPerformed

	private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jTable1MouseClicked
		int baris = jTable1.rowAtPoint(evt.getPoint());
		jTextField1.setText(jTable1.getValueAt(baris, 0).toString());
		jTextArea1.setText(jTable1.getValueAt(baris, 1).toString());
		jComboBox1.setSelectedItem(jTable1.getValueAt(baris, 3).toString());
		jTextField2.setText(jTable1.getValueAt(baris, 4).toString());
	}// GEN-LAST:event_jTable1MouseClicked

	private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton2ActionPerformed
		try {
			String sql = "UPDATE bug SET bug = '" + jTextArea1.getText() + "', status = '"
					+ jComboBox1.getSelectedItem() + "', solver = '" + jTextField2.getText() + "' WHERE id = '"
					+ jTextField1.getText() + "'";
			java.sql.Connection conn = (Connection) Configuration.configDB();
			java.sql.PreparedStatement pst = conn.prepareStatement(sql);
			pst.execute();
			hafizh();
			JOptionPane.showMessageDialog(null, "Data Berhasil Di Edit");
		} catch (Exception e) {
			JOptionPane.showMessageDialog(null, "Perubahan Data Gagal\nError: " + e.getMessage());
		}
	}// GEN-LAST:event_jButton2ActionPerformed

	private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton3ActionPerformed
		int reply = JOptionPane.showConfirmDialog(null, "Are you sure you want to delete?",
				"Deleting Bug-" + jTextField1.getText() + "...", JOptionPane.YES_NO_OPTION);
		if (reply == JOptionPane.YES_OPTION) {
			try {
				String sql = "delete from bug where id='" + jTextField1.getText() + "'";
				java.sql.Connection conn = (Connection) Configuration.configDB();
				java.sql.PreparedStatement pst = conn.prepareStatement(sql);
				pst.execute();
				hafizh();
				JOptionPane.showMessageDialog(this, "berhasil di hapus");
			} catch (Exception e) {
				JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
			}
		}
	}// GEN-LAST:event_jButton3ActionPerformed

	private void jPanel1KeyPressed(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_jPanel1KeyPressed

	}// GEN-LAST:event_jPanel1KeyPressed

	private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextField3ActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_jTextField3ActionPerformed

	private void jTextField3KeyPressed(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_jTextField3KeyPressed
		DefaultTableModel model = new DefaultTableModel();
		model.addColumn("ID");
		model.addColumn("Bug");
		model.addColumn("Status");
		model.addColumn("Solver");
		try {
			String sql;
			if (jTextField3.getText() == "") {
				sql = "select * from bug";
			} else {
				sql = "select * from bug WHERE bug LIKE '%" + jTextField3.getText() + "%' OR status LIKE '%"
						+ jTextField3.getText() + "%' OR solver LIKE '%" + jTextField3.getText() + "%'";
			}
			java.sql.Connection conn = (Connection) Configuration.configDB();
			java.sql.Statement stm = conn.createStatement();
			java.sql.ResultSet res = stm.executeQuery(sql);
			while (res.next()) {
				model.addRow(new Object[] { res.getString(1), res.getString(2), res.getString(3), res.getString(4) });
			}
			jTable1.setModel(model);
		} catch (Exception e) {
		}
	}// GEN-LAST:event_jTextField3KeyPressed

	private void hafizh() {
		load_table();
		kosong();
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
		// (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
		 * look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(Bugzilla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(Bugzilla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(Bugzilla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(Bugzilla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new Bugzilla().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton2;
	private javax.swing.JButton jButton3;
	private javax.swing.JButton jButton4;
	private javax.swing.JButton jButton5;
	private javax.swing.JComboBox<String> jComboBox1;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JMenu jMenu1;
	private javax.swing.JMenu jMenu2;
	private javax.swing.JMenu jMenu3;
	private javax.swing.JMenuBar jMenuBar1;
	private javax.swing.JMenuItem jMenuItem2;
	private javax.swing.JMenuItem jMenuItem3;
	private javax.swing.JMenuItem jMenuItem4;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JScrollPane jScrollPane2;
	private javax.swing.JTable jTable1;
	private javax.swing.JTextArea jTextArea1;
	private javax.swing.JTextField jTextField1;
	private javax.swing.JTextField jTextField2;
	private javax.swing.JTextField jTextField3;
	// End of variables declaration//GEN-END:variables
}
